site_name: MkDocs Starter
site_description: A comprehensive starter project for MkDocs with Nix flake support
site_author: Your Name
site_url: https://yourdomain.com

# Repository
repo_name: mkdocs-starter
repo_url: https://github.com/yourusername/mkdocs-starter
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.action.edit
    - content.action.view

  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

# Markdown extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html

# Custom CSS
extra_css:
  - assets/css/custom.css

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - API Documentation:
    - Overview: api/overview.md
    - Reference: api/reference.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername

# Copyright
copyright: Copyright &copy; 2023 Your Name